In [73]:
import pandas as pd

In [74]:
# Read the data salario
df = pd.read_csv('E:\\OneDrive - Odemi Lab\\Odemilab\\DATA SCIENCE\\DATA REYNOSA 2022\\Distribucion-fuerza-laboral-Total-por-ocupaciones-en-TamaulipasColoreado-por-salario-promedio-mensual-en-cuarto-trimestre-de-2022.csv')

In [75]:
df.head()

,Category ID,Category,Group ID,Group,Subgroup ID,Subgroup,Occupation ID,Occupation,Year,Quarter ID,Quarter,Workforce,Monthly Wage,Monthly Wage Growth,Monthly Wage Growth Value,percentage,lastPeriod
0,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,111,"Funcionarios, Legisladores y Autoridades Guber...",1113,Presidentes y Autoridades Municipales,2022,20224,2022-Q4,582,35000.000000,1.00000,35000.000000,0.000364,0.000000
1,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,112,Presidentes y Directores Generales,1122,Presidentes y Directores Generales en Instituc...,2022,20224,2022-Q4,508,61811.023622,1.00000,61811.023622,0.000318,0.000000
2,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,113,"Directores de Organizaciones Políticas, Sindic...",1131,Directores de Organizaciones Políticas,2022,20224,2022-Q4,93,8000.000000,1.00000,8000.000000,0.000058,0.000000
3,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,113,"Directores de Organizaciones Políticas, Sindic...",1135,Directores de Organizaciones Civiles y Religiosas,2022,20224,2022-Q4,455,0.000000,1.00000,0.000000,0.000284,0.000000
4,1,"Funcionarios, Directores y Jefes",12,Directores y Gerentes en Servicios Financieros...,121,Directores y Gerentes en Servicios Financieros...,1211,"Directores y Gerentes en Administración, Recur...",2022,20224,2022-Q4,1245,10763.052209,-0.53867,-12567.434312,0.000778,23330.486521

In [76]:
# create a new column called 'AreaID' with string 'ingenieros' if 'Subgroup' contains a string 'Ing' and 'licenciados' if 'Subgroup' contains a string 'Adm'
df['Area ID'] = df['Subgroup'].apply(lambda x: 7 if 'Ing' in x else 4 if 'Adm' in x else 0)

In [77]:
df.head()

,Category ID,Category,Group ID,Group,Subgroup ID,Subgroup,Occupation ID,Occupation,Year,Quarter ID,Quarter,Workforce,Monthly Wage,Monthly Wage Growth,Monthly Wage Growth Value,percentage,lastPeriod,Area ID
0,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,111,"Funcionarios, Legisladores y Autoridades Guber...",1113,Presidentes y Autoridades Municipales,2022,20224,2022-Q4,582,35000.000000,1.00000,35000.000000,0.000364,0.000000,0
1,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,112,Presidentes y Directores Generales,1122,Presidentes y Directores Generales en Instituc...,2022,20224,2022-Q4,508,61811.023622,1.00000,61811.023622,0.000318,0.000000,0
2,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,113,"Directores de Organizaciones Políticas, Sindic...",1131,Directores de Organizaciones Políticas,2022,20224,2022-Q4,93,8000.000000,1.00000,8000.000000,0.000058,0.000000,0
3,1,"Funcionarios, Directores y Jefes",11,Funcionarios y Altas Autoridades de los Sector...,113,"Directores de Organizaciones Políticas, Sindic...",1135,Directores de Organizaciones Civiles y Religiosas,2022,20224,2022-Q4,455,0.000000,1.00000,0.000000,0.000284,0.000000,0
4,1,"Funcionarios, Directores y Jefes",12,Directores y Gerentes en Servicios Financieros...,121,Directores y Gerentes en Servicios Financieros...,1211,"Directores y Gerentes en Administración, Recur...",2022,20224,2022-Q4,1245,10763.052209,-0.53867,-12567.434312,0.000778,23330.486521,4

In [78]:
import matplotlib.pyplot as plt
import seaborn as sns

In [79]:
dfmatricula = pd.read_csv('E:\\OneDrive - Odemi Lab\\Odemilab\\DATA SCIENCE\\DATA REYNOSA 2022\\Matriculas-segun-campo-de-formacion-en-Reynosa-Totales-2021.csv')

In [80]:
dfmatricula.head()

,Area ID,Area,Field ID,Field,Subfield ID,Subfield,Year,Students,Students Growth,Students Growth Value,percentage
0,1,Educación,11,Ciencias de la educación y pedagogía,110,Planes multidisciplinarios o generales del cam...,2021,80,-0.111111,-10,0.002495
1,1,Educación,11,Ciencias de la educación y pedagogía,111,Diseño curricular y pedagogía,2021,351,-0.231947,-106,0.010949
2,1,Educación,11,Ciencias de la educación y pedagogía,112,"Planeación, evaluación e investigación educativa",2021,68,-0.139241,-11,0.002121
3,1,Educación,11,Ciencias de la educación y pedagogía,113,Orientación e intervención educativa,2021,297,-0.041935,-13,0.009264
4,1,Educación,11,Ciencias de la educación y pedagogía,115,Ciencias de la educación,2021,484,-0.150877,-86,0.015097

In [81]:
#rename AreaID column to AreaIDMatricula
dfmatricula.rename(columns={'AreaID':'AreaID'}, inplace=True)

In [82]:
df.dtypes

Category ID                    int64
Category                      object
Group ID                       int64
Group                         object
Subgroup ID                    int64
Subgroup                      object
Occupation ID                  int64
Occupation                    object
Year                           int64
Quarter ID                     int64
Quarter                       object
Workforce                      int64
Monthly Wage                 float64
Monthly Wage Growth          float64
Monthly Wage Growth Value    float64
percentage                   float64
lastPeriod                   float64
Area ID                        int64
dtype: object

In [83]:
dfmatricula.dtypes

Area ID                    int64
Area                      object
Field ID                   int64
Field                     object
Subfield ID                int64
Subfield                  object
Year                       int64
Students                   int64
Students Growth          float64
Students Growth Value      int64
percentage               float64
dtype: object

In [84]:
# merge a dataframe df and dfmatricula on 'AreaID' column
df = pd.merge(df, dfmatricula, on='Area ID')

In [85]:
df.head(3)

,Category ID,Category,Group ID,Group,Subgroup ID,Subgroup,Occupation ID,Occupation,Year_x,Quarter ID,...,Area,Field ID,Field,Subfield ID,Subfield,Year_y,Students,Students Growth,Students Growth Value,percentage_y
0,1,"Funcionarios, Directores y Jefes",12,Directores y Gerentes en Servicios Financieros...,121,Directores y Gerentes en Servicios Financieros...,1211,"Directores y Gerentes en Administración, Recur...",2022,20224,...,Administración y negocios,41,Negocios y contabilidad,411,Negocios y comercio,2021,1591,-0.043870,-73,0.049627
1,1,"Funcionarios, Directores y Jefes",12,Directores y Gerentes en Servicios Financieros...,121,Directores y Gerentes en Servicios Financieros...,1211,"Directores y Gerentes en Administración, Recur...",2022,20224,...,Administración y negocios,41,Negocios y contabilidad,412,Mercadotecnia y publicidad,2021,1100,0.353014,287,0.034312
2,1,"Funcionarios, Directores y Jefes",12,Directores y Gerentes en Servicios Financieros...,121,Directores y Gerentes en Servicios Financieros...,1211,"Directores y Gerentes en Administración, Recur...",2022,20224,...,Administración y negocios,41,Negocios y contabilidad,413,"Finanzas, banca y seguros",2021,19,-0.406250,-13,0.000593

In [86]:
df.dtypes

Category ID                    int64
Category                      object
Group ID                       int64
Group                         object
Subgroup ID                    int64
Subgroup                      object
Occupation ID                  int64
Occupation                    object
Year_x                         int64
Quarter ID                     int64
Quarter                       object
Workforce                      int64
Monthly Wage                 float64
Monthly Wage Growth          float64
Monthly Wage Growth Value    float64
percentage_x                 float64
lastPeriod                   float64
Area ID                        int64
Area                          object
Field ID                       int64
Field                         object
Subfield ID                    int64
Subfield                      object
Year_y                         int64
Students                       int64
Students Growth              float64
Students Growth Value          int64
percentage_y                 float64
dtype: object

In [88]:
dfworkers = pd.read_csv('E:\\OneDrive - Odemi Lab\\Odemilab\\DATA SCIENCE\\DATA REYNOSA 2022\\Distribucion-fuerza-laboral-Total-por-ocupaciones-en-Tamaulipascuarto-trimestre-de-2022.csv')

In [91]:
dfworkers.columns

Index(['Category ID', 'Category', 'Group ID', 'Group', 'Subgroup ID',
       'Subgroup', 'Occupation ID', 'Occupation', 'Year', 'Quarter ID',
       'Quarter', 'Workforce', 'Workforce Growth', 'Workforce Growth Value',
       'percentage', 'lastPeriod'],
      dtype='object')

In [92]:
# merge a dataframe df and dfworkers on 'Occupation ID' column
df = pd.merge(df, dfworkers, on='Occupation ID')

In [93]:
df.dtypes

Category ID_x                  int64
Category_x                    object
Group ID_x                     int64
Group_x                       object
Subgroup ID_x                  int64
Subgroup_x                    object
Occupation ID                  int64
Occupation_x                  object
Year_x                         int64
Quarter ID_x                   int64
Quarter_x                     object
Workforce_x                    int64
Monthly Wage                 float64
Monthly Wage Growth          float64
Monthly Wage Growth Value    float64
percentage_x                 float64
lastPeriod_x                 float64
Area ID                        int64
Area                          object
Field ID                       int64
Field                         object
Subfield ID                    int64
Subfield                      object
Year_y                         int64
Students                       int64
Students Growth              float64
Students Growth Value          int64
percentage_y                 float64
Category ID_y                  int64
Category_y                    object
Group ID_y                     int64
Group_y                       object
Subgroup ID_y                  int64
Subgroup_y                    object
Occupation_y                  object
Year                           int64
Quarter ID_y                   int64
Quarter_y                     object
Workforce_y                    int64
Workforce Growth             float64
Workforce Growth Value         int64
percentage                   float64
lastPeriod_y                   int64
dtype: object

In [104]:
!pip install plotly-express -q
!pip install kaleido -q

In [105]:
import plotly.express as px

In [110]:
# define the plotly template. some other examples are: 'plotly', 'plotly_white', 'plotly_dark', 'ggplot2', 'seaborn', 'simple_white', 'none'
plotly_template = 'presentation'

In [117]:
# create a 20x50 scatter plot of 'Workforce Growth Value' and 'Monthly Wage Growth Value' with 'licenciados' and 'ingenieros' colors with regression line
fig = px.scatter(df, x='Workforce Growth Value', y='Monthly Wage Growth Value', color='Area', trendline='ols', template=plotly_template, width=1000, height=500, title='Workforce Growth vs Monthly Wage Growth')

In [118]:
fig.show()